### ISSUE TITLE
19/08/2017 - Website meeting #1

### ISSUE THREAD

**Issue by ghost** [WarwickTECH/website#3]
# Participants
@IEavan 
@victoriasze 

# Issues tracking
No pending issues 

# Topics
## Design (Victoria)
- Pages layout
- Need of at least 2 design samples.

## Backend (Eavan)
- Technologies? Django
- Work on the back-bone for
  - Job boards
  - Resource hub
  - Login / Sign up

# New Issues
https://github.com/WarwickTECH/website/issues/2
https://github.com/WarwickTECH/website/issues/1

**Comment by IEavan** [comment]
No longer relevant, closing this issue
